export const getData = function() {
    return [
        {
            strName: "lagman",
            srtСategory: "second course",
            srtImg: "https://www.vkusnyblog.ru/wp-content/uploads/2014/07/lagman.jpg",
            amountOfIngredients: "for 6 servings",
            strIngredient1: "tomato",
            strIngredient2: "spices",
            strIngredient3: "onion",
            strIngredient4: "garlic",
            strIngredient5: "meat",
            strIngredient6: "eggplant",
            strIngredient7: "pepper",
            strIngredient8: "water",
            strIngredient9: "egg",
            strIngredient10: "flour",
            strMeasure1: "3 pieces",
            strMeasure2: "1 soup spoon",
            strMeasure3: "2 pieces",
            strMeasure4: "4 tine",
            strMeasure5: "600 grams",
            strMeasure6: "1 pieces",
            strMeasure7: "4 pieces",
            strMeasure8: "1 liter",
            strMeasure9: "3 pieces",
            strMeasure10: "450 grams",
            strInstructions: "https://www.vkusnyblog.ru/recipe/lagman/",
            strVideo: "https://www.youtube.com/watch?v=dFGZs96aJEw&t=1s"
        },
        {
            strName: "Shorpo",
            strCategory: "First course",
            strImg:"https://blog.russianfoodusa.com/wp-content/uploads/2015/08/Shorpo-1.jpg",
            amountOfIngredients: "for 6 servings",
            strIngredient1: "lamb with bones",
            strIngredient2: "tomatoes",
            strIngredient3: "potatoes",
            strIngredient4: "onion",
            strIngredient5: "lamb fat",
            strIngredient6: "Greens,Pepper,Salt", 
            strMeasure1: "500 g",
            strMeasure2: "200 g",
            strMeasure3: "500 g",
            strMeasure4: "100 g",
            strMeasure5: "150 g",
            strInstruction:"Slice lamb (with bones), rub with salt and pepper and put in a pan with fat.Fry until light brown.Then add sliced onion, tomatoes to the meat and pour in water.Bring to boil and cook for 30 minutes.",
            strVideo:"https://www.youtube.com/watch?v=HoFuEJ_iTQc"
          },
          {
            strName:"Boorsok",
            strCategory:"baking",
            strImg:"https://th.bing.com/th/id/R.747d7fe400cbc73ff764db80a972ede3?rik=jFNyvjEdcoOrWg&riu=http%3a%2f%2fworld.lisagermany.com%2fwp-content%2fuploads%2f2017%2f05%2f20170424_142943.jpg&ehk=VpDhTgWrRpNVVHNRp2i0ayYYbb%2fBcJlS45HkhENOoLM%3d&risl=&pid=ImgRaw&r=0",
            amountOfIngredients: "for 10 servings",
            strIngredient1:"Butter,yeast,sugar",
            strIngredient2:"Flour",
            strIngredient3:"Milk",
            strIngredient4:"Salt",
            strIngredient5:"Yeast",
            strIngredient6:"Sugar",
            strInstructions:"The dough for boorsok is more often used yeast, about the same as it is prepared for pizza. Sliced pieces of rolled dough are fried in oil for 20-30 seconds, then transferred from the cauldron to a sieve or colander to properly drain the oil. Slicing depends on the imagination of the cook. You can cut into squares, circles, lozenges, rectangles, use curly knives. Cooking boorsok is one continuous pleasure, you will easily and quickly master the technology of its preparation. ",
            strVideo:"https://www.youtube.com/watch?v=9v8jPC7Cj8s",
          },
          { 
            strName: "Shashlyk",
            strCategory: "Second course",
            strImg:"https://rutxt.ru/files/15888/original/02658cf8a4.JPG",
            amountOfIngredients: "for 6 servings",
            strMeasure1: "Lamb", 
            strIngredient2: "Liver",
            strIngredient3: "Onion",
            strMeasure1: "2 kg",
            strMeasure2: "2 kg",
            strMeasure3: "1 kg",
            strInstructions:"Shishkebek is a traditional Kyrgyz shish kebab made from liver or mutton and served with vinegar, onions and salad.",
            strVideo:"https://youtu.be/3qlsPBtm6dU",
          },
         
          {
            strName: "Chicken soup",
            strCategory:"First course",
            strImg:"https://s1.webspoon.ru/receipts/2012/9/2975/orig_2975_0_xxl.jpg",
            strIngredient1: "Chikcen meet",
            strIngredient2: "Onion",
            strIngredient3:"Potato",
            strIngredient4: "Salt and pepper",
            strMeasure1:"1 kg",
            strMeasure2: "0,3 gr",
            strMeasure3: "0,3 gr",
            strInstructions: "Put the washed hams in a saucepan, pour cold water, put on high heat. After 30 minutes, we catch the onion, put the carrot, diced. After 5 minutes, add the peeled and sliced potatoes, taste for salt. Cook for another 10-15 minutes.",
            strVideo:"https://youtu.be/qhH131jxdvQ",
           },
   
        {
            strName: "beshBarmak",
            srtСategory: "second course",
            srtImg: "https://pbs.twimg.com/media/EYijbl3WkAAREVj?format=jpg&name=large",
            amountOfIngredients: "for 4 servings",
            strIngredient1: "lamb",
            strIngredient2: "water",
            strIngredient3: "onions",
            strIngredient4: "salt",
            strIngredient5: "egg",
            strIngredient6: "flour",
            strIngredient7: "pepper",
            strIngredient8: "fresh dill weed",
            strIngredient9: "bay leaf",
            strIngredient10: "broth",
            strMeasure1: "1.5 kg",
            strMeasure2: "5 l",
            strMeasure3: "3",
            strMeasure4: "1 tsp",
            strMeasure5: "1",
            strMeasure6: "500 gr",
            strMeasure7: "1 tsp",
            strMeasure8: "1 tbsp",
            strMeasure9: "2",
            strMeasure10: "4 l",
            strInstructions: "https://ingmar.app/blog/recipe-the-national-dish-of-kyrgyzstan-besh-barmak/",
            strVideo: "https://www.youtube.com/watch?v=NeQEWHBzgBU"
        },

        {
            strName: "jarma",
            srtСategory: "drinks",
            srtImg: "http://kg.kabar.kg/site/assets/files/16620/photo5.730x0.jpg",
            amountOfIngredients: "for 6 servings",
            strIngredient1: "crushed wheat",
            strIngredient2: "sheep fat",
            strIngredient3: "water",
            strIngredient4: "flour",
            strIngredient5: "fermented jarma",
            strIngredient6: "salt",
            strMeasure1: "1 cup",
            strMeasure2: "1 tbsp",
            strMeasure3: "5 l",
            strMeasure4: "2 tbsp",
            strMeasure5: "0.5 l",
            strMeasure6: "1 tsp",
            strInstructions: "https://www.peacecorps.gov/stories/how-to-make-jarma-a-traditional-kyrgyz-drink/",
            strVideo: "https://www.youtube.com/watch?v=pyuag-_WqvM"
        },
    ]
}   
